server:
  contextPath: /sasb
  port: 8080
  ssl:
    enabled: true
    key-alias: 1
    key-store: classpath:certificates/COMPESA2024.jks
    key-store-type: pkcs12
    key-store-password: COMPESA2024
spring:
  servlet:
    multipart:
      max-file-size: 150MB
      max-request-size: 150MB
springdoc:
  api:
    docs:
      enabled: true
api:
  security:
    token:
      secret:
        key: "@sasbcomp3sa2023!"
      issuer: sasb-compesa-api
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:oracle:thin:@//192.168.1.220:1521/BLCMCOP
    username: sic
    password: blcmcop
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect